'use strict';

const crypto = require('crypto'); const path = require('path'); const { fork } = require('child_process'); const mongoose = require('mongoose');
const { Provider } = require('../modules/providers/provider.model'); const { ProviderProduct } = require('../modules/providers/providerProduct.model'); const { Product } = require('../modules/products/product.model'); const { Order, ORDER_STATUS, ORDER_EXECUTION_TYPES } = require('../modules/orders/order.model'); const { User, ROLES, USER_STATUS } = require('../modules/users/user.model'); const Group = require('../modules/groups/group.model'); const { CanonicalB2BAdapter } = require('../modules/providers/adapters/canonicalB2B.adapter'); const { getProviderAdapter } = require('../modules/providers/adapters/adapter.factory'); const { syncProviderProducts } = require('../modules/providers/providerProductSync.service'); const { executeOrder } = require('../modules/orders/orderFulfillment.service');

const fixture = path.join(__dirname, 'fixtures', 'canonicalB2B.upstreamServer.js'); const token = crypto.randomBytes(32).toString('hex'); const productId = 700001; const directReference = 'LOCAL-DIRECT-001'; const fulfillmentReference = 930001;
let upstream; let upstreamPort; let upstreamUserId; let provider; let adapter;
const upstreamRequest = (type, data = {}) => new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error(`Timed out waiting for upstream ${type}`)), 15000); const listener = (message) => { if (message.type === 'error') { clearTimeout(timer); upstream.off('message', listener); return reject(new Error(message.message)); } if (message.type === type) { clearTimeout(timer); upstream.off('message', listener); resolve(message.data); } }; upstream.on('message', listener); upstream.send({ type, data }); });
const startUpstream = () => new Promise((resolve, reject) => { upstream = fork(fixture, [], { cwd: path.resolve(__dirname, '../..'), stdio: ['ignore', 'ignore', 'ignore', 'ipc'], env: { ...process.env, NODE_ENV: 'test', SAFE_LOCAL_PRODUCTION_MODE: 'true', UPSTREAM_TEST_MONGO_URI: process.env.MONGO_TEST_URI, UPSTREAM_TEST_DB_NAME: `ms_b2b_upstream_${process.pid}_${Date.now()}` } }); const timer = setTimeout(() => reject(new Error('Timed out starting local upstream')), 30000); upstream.once('message', (message) => { clearTimeout(timer); if (message.type === 'ready') { upstreamPort = message.port; resolve(); } else reject(new Error(message.message || 'Local upstream failed')); }); upstream.once('error', reject); });
const stopUpstream = async () => { if (!upstream || upstream.killed) return; await new Promise((done) => { const timer = setTimeout(() => { upstream.kill(); done(); }, 5000); upstream.once('exit', () => { clearTimeout(timer); done(); }); upstream.send({ type: 'shutdown' }); }); };

beforeAll(async () => {
    await startUpstream(); const seeded = await upstreamRequest('seed', { token, compatProductId: productId }); upstreamUserId = seeded.userId;
    await mongoose.connect(process.env.MONGO_TEST_URI, { dbName: `ms_b2b_downstream_${process.pid}_${Date.now()}` }); await Promise.all(Object.values(mongoose.models).map((model) => model.syncIndexes().catch(() => undefined)));
    provider = await Provider.create({ name: 'Local Canonical Upstream', slug: 'local-canonical-upstream', adapterType: 'canonical-b2b', baseUrl: `http://127.0.0.1:${upstreamPort}/client/api`, apiToken: token, isActive: true, syncInterval: 0 }); adapter = getProviderAdapter(provider, { timeoutMs: 5000 });
});
afterAll(async () => { await mongoose.disconnect(); await stopUpstream(); });

describe('Canonical B2B local upstream/downstream integration', () => {
    test('gets profile and products over real local HTTP then syncs a ProviderProduct', async () => {
        expect(adapter).toBeInstanceOf(CanonicalB2BAdapter); await expect(adapter.getBalance()).resolves.toMatchObject({ balance: '100.000000', currency: 'USD' });
        const products = await adapter.getProducts(); expect(products).toHaveLength(1); expect(products[0]).toMatchObject({ externalProductId: String(productId), rawName: 'Local Canonical Product', rawPrice: '10', minQty: 1, maxQty: 1, rawPayload: { fields: [expect.objectContaining({ key: 'player_id' })] } });
        const result = await syncProviderProducts(provider._id); expect(result).toMatchObject({ totalFetched: 1 }); expect(result.errors).toEqual([]); expect(await ProviderProduct.findOne({ provider: provider._id, externalProductId: String(productId) }).lean()).toMatchObject({ rawName: 'Local Canonical Product', rawPrice: '10', isActive: true });
    });

    test('places one upstream order, safely replays it, and checks ID plus UUID', async () => {
        const first = await adapter.placeOrder({ externalProductId: String(productId), quantity: 1, referenceId: directReference, player_id: '123456789' }); expect(first).toMatchObject({ success: true, providerOrderId: expect.stringMatching(/^ID_/) });
        expect(await upstreamRequest('last-order-request')).toEqual({ method: 'POST', path: '/client/api/orders', body: { product_id: productId, qty: 1, order_uuid: directReference, params: { player_id: '123456789' } } });
        expect(await upstreamRequest('snapshot', { userId: upstreamUserId, idempotencyKey: directReference })).toMatchObject({ orderCount: 1, walletBalance: 90 });
        const replay = await adapter.placeOrder({ externalProductId: String(productId), quantity: 1, referenceId: directReference, player_id: '123456789' }); expect(replay).toMatchObject({ success: true, providerOrderId: first.providerOrderId }); expect(await upstreamRequest('snapshot', { userId: upstreamUserId, idempotencyKey: directReference })).toMatchObject({ orderCount: 1, walletBalance: 90 });
        await expect(adapter.checkOrder(first.providerOrderId)).resolves.toMatchObject({ providerOrderId: first.providerOrderId }); await expect(adapter.checkOrderByReference(directReference)).resolves.toMatchObject({ found: true, providerOrderId: first.providerOrderId });
    });

    test('real downstream fulfillment uses persisted orderNumber as the upstream UUID', async () => {
        const providerProduct = await ProviderProduct.findOne({ provider: provider._id, externalProductId: String(productId) }); const group = await Group.create({ name: 'Local downstream group', percentage: 0, isActive: true }); const user = await User.create({ name: 'Local downstream customer', email: `downstream-${Date.now()}@test.invalid`, password: 'TestPassword@1', role: ROLES.CUSTOMER, status: USER_STATUS.ACTIVE, verified: true, groupId: group._id, walletBalance: 100, creditLimit: 0, creditUsed: 0 }); const product = await Product.create({ name: 'Downstream Canonical Product', basePrice: '10', minQty: 1, maxQty: 1, isActive: true, executionType: ORDER_EXECUTION_TYPES.AUTOMATIC, provider: provider._id, providerProduct: providerProduct._id, providerMapping: { player_id: 'player_id' } });
        const order = await Order.create({ userId: user._id, productId: product._id, orderNumber: fulfillmentReference, quantity: 1, unitPrice: '10', totalPrice: '10', basePriceSnapshot: '10', markupPercentageSnapshot: 0, finalPriceCharged: '10', groupIdSnapshot: group._id, walletDeducted: 10, creditUsedAmount: '0', chargedAmount: 10, currency: 'USD', status: ORDER_STATUS.PROCESSING, executionType: ORDER_EXECUTION_TYPES.AUTOMATIC, customerInput: { values: { player_id: '123456789' }, fieldsSnapshot: [] } });
        expect(await executeOrder(order._id)).toMatchObject({ placed: true }); const fresh = await Order.findById(order._id).lean(); const upstreamOrder = await upstreamRequest('snapshot', { userId: upstreamUserId, idempotencyKey: String(fulfillmentReference) }); expect(fresh).toMatchObject({ status: ORDER_STATUS.PROCESSING, providerStatus: 'wait', providerOrderId: upstreamOrder.order.compatOrderId }); expect(upstreamOrder).toMatchObject({ orderCount: 2, walletBalance: 80, order: { idempotencyKey: String(fulfillmentReference) } });
    });
});
